INSERT INTO PROPERTIES (
    owner_id,
    created_by,
    address_id,
    description,
    price,
    property_type,
    floor,
    bedrooms,
    bathrooms,
    property_realtor_commission,
    buyer_realtor_commission,
    area_space,
    year_built,
    latitude,
    longitude,
    status,
    created_at,
    last_updated ,
    image_url 
)
VALUES(
    :owner_id,
    :created_by,
    :address_id,
    :description,
    :price,
    :property_type,
    :floor,
    :bedrooms,
    :bathrooms,
    :property_realtor_commission,
    :buyer_realtor_commission,
    :area_space,
    :year_built,
    :latitude,
    :longitude,
    :status,
    :created_at,
    :last_updated ,
    :image_url
)
RETURNING property_id;