INSERT INTO PROPERTIES (
    owner_id,
    created_by,
    description,
    show_inst,
    price,
    property_type,
    bedrooms,
    bathrooms,
    property_realtor_commission,
    buyer_realtor_commission,
    area_space,
    year_built,
    latitude,
    longitude,
    status,
    trans_type,
    exp_date,
    created_at,
    last_updated ,
    images_urls,
    mls_num
)
VALUES(
    :owner_id,
    :created_by,
    :description,
    :show_inst,
    :price,
    :property_type,
    :bedrooms,
    :bathrooms,
    :property_realtor_commission,
    :buyer_realtor_commission,
    :area_space,
    :year_built,
    :latitude,
    :longitude,
    :status,
    :trans_type,
    :exp_date,
    :created_at,
    :last_updated ,
    :images_urls,
    :mls_num
)
RETURNING property_id;