name: Run Unit Tests (PostgreSQL)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      DATABASE_TEST_USERNAME: ${{ secrets.DATABASE_TEST_USERNAME }}
      DATABASE_TEST_PASSWORD: ${{ secrets.DATABASE_TEST_PASSWORD }}
      DATABASE_TEST_HOST: ${{ secrets.DATABASE_TEST_HOST }}
      DATABASE_TEST_PORT: ${{ secrets.DATABASE_TEST_PORT }}
      DATABASE_TEST_NAME: ${{ secrets.DATABASE_TEST_NAME }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest -v
