name: Run Unit Tests (PostgreSQL)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: nrep_test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      ENV: TEST
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: nrep_test_database

      DATABASE_TEST_USERNAME: postgres
      DATABASE_TEST_PASSWORD: 1234
      DATABASE_TEST_HOST: localhost
      DATABASE_TEST_PORT: 5432
      DATABASE_TEST_NAME: nrep_test_database

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Debug Postgres logs
      run: |
        docker ps -a
        docker logs $(docker ps -q --filter "ancestor=postgres:14")
        
    - name: Wait for Postgres to be ready
      run: |
          until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" >/dev/null 2>&1; do
              echo "Waiting for postgres at $DB_HOST:$DB_PORT..."
              sleep 2
          done
          echo "Postgres is ready!"

    - name: Test with pytest
      run: |
        pytest -v
